package com.dremio.udf.vector;

import com.dremio.exec.expr.SimpleFunction;
import com.dremio.exec.expr.annotations.FunctionTemplate;
import com.dremio.exec.expr.annotations.Output;
import com.dremio.exec.expr.annotations.Param;
import javax.inject.Inject;
import org.apache.arrow.memory.ArrowBuf;
import org.apache.arrow.vector.holders.NullableFloat8Holder;
import org.apache.arrow.vector.holders.NullableVarCharHolder;
import org.apache.arrow.vector.holders.NullableIntHolder;
import org.apache.arrow.vector.holders.Float8Holder;
import org.apache.arrow.vector.holders.IntHolder;

/**
 * Dremio SQL UDFs for vector similarity and distance operations.
 *
 * All functions accept vectors as VARCHAR JSON-array strings, e.g.:
 *   "[0.12, -0.45, 0.88, 0.03]"
 *
 * Available functions:
 *
 *   COSINE_SIMILARITY(vec1, vec2)          → DOUBLE  [-1, 1]
 *   COSINE_DISTANCE(vec1, vec2)            → DOUBLE  [0, 2]
 *   L2_DISTANCE(vec1, vec2)               → DOUBLE  [0, ∞)
 *   L2_DISTANCE_SQUARED(vec1, vec2)       → DOUBLE  [0, ∞)  (faster, no sqrt)
 *   DOT_PRODUCT(vec1, vec2)               → DOUBLE
 *   L1_DISTANCE(vec1, vec2)               → DOUBLE  [0, ∞)
 *   VECTOR_NORM(vec)                      → DOUBLE
 *   VECTOR_DIMS(vec)                      → INT
 *   VECTOR_DISTANCE(vec1, vec2, metric)   → DOUBLE  (generic dispatcher)
 *
 * Example queries:
 *
 *   -- Semantic search: find top-10 most similar documents to a query vector
 *   SELECT id, text, COSINE_SIMILARITY(embedding, :query_vec) AS score
 *   FROM my_table.embeddings
 *   ORDER BY score DESC
 *   LIMIT 10;
 *
 *   -- Nearest neighbours by L2 distance
 *   SELECT id, L2_DISTANCE(embedding, :query_vec) AS dist
 *   FROM my_table.embeddings
 *   ORDER BY dist ASC
 *   LIMIT 10;
 */
public class VectorDistanceFunctions {

  // ── Helper: extract String from NullableVarCharHolder ─────────────────────
  // NOTE: eval() is code-generated by Dremio/Janino — all class references
  //       must be fully qualified. No imports are available inside eval().

  // ── COSINE_SIMILARITY ─────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "cosine_similarity",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class CosineSimilarity implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.cosineSimilarity(a, b);
    }
  }

  // ── COSINE_DISTANCE ───────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "cosine_distance",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class CosineDistance implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.cosineDistance(a, b);
    }
  }

  // ── L2_DISTANCE ───────────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "l2_distance",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class L2Distance implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.l2Distance(a, b);
    }
  }

  // ── L2_DISTANCE_SQUARED ───────────────────────────────────────────────────

  @FunctionTemplate(
      name = "l2_distance_squared",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class L2DistanceSquared implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.l2DistanceSquared(a, b);
    }
  }

  // ── DOT_PRODUCT ───────────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "dot_product",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class DotProduct implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.dotProduct(a, b);
    }
  }

  // ── L1_DISTANCE ───────────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "l1_distance",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class L1Distance implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.l1Distance(a, b);
    }
  }

  // ── VECTOR_NORM ───────────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "vector_norm",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorNorm implements SimpleFunction {
    @Param  NullableVarCharHolder vec;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec.end - vec.start];
      vec.buffer.getBytes(vec.start, b1);
      String s = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s);
      out.value = com.dremio.udf.vector.VectorUtils.norm(a);
    }
  }

  // ── VECTOR_DIMS ───────────────────────────────────────────────────────────

  @FunctionTemplate(
      name = "vector_dims",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorDims implements SimpleFunction {
    @Param  NullableVarCharHolder vec;
    @Output NullableIntHolder     out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec.end - vec.start];
      vec.buffer.getBytes(vec.start, b1);
      String s = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      out.value = com.dremio.udf.vector.VectorUtils.dims(s);
    }
  }

  // ── VECTOR_DISTANCE (generic dispatcher) ──────────────────────────────────

  @FunctionTemplate(
      name = "vector_distance",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorDistance implements SimpleFunction {
    @Param  NullableVarCharHolder vec1;
    @Param  NullableVarCharHolder vec2;
    @Param  NullableVarCharHolder metric;
    @Output NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec1.end - vec1.start];
      vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start];
      vec2.buffer.getBytes(vec2.start, b2);
      byte[] bm = new byte[metric.end - metric.start];
      metric.buffer.getBytes(metric.start, bm);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      String sm = new String(bm, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      out.value = com.dremio.udf.vector.VectorUtils.dispatch(a, b, sm);
    }
  }

  // ── VECTOR_IS_VALID ───────────────────────────────────────────────────────

  /**
   * Returns TRUE if the input string is a parseable, non-empty vector JSON array.
   * Useful for data quality checks and filtering out malformed embeddings.
   *
   * Example:
   *   VECTOR_IS_VALID('[0.1, 0.2, 0.3]')  →  TRUE
   *   VECTOR_IS_VALID('[]')               →  FALSE
   *   VECTOR_IS_VALID('not a vector')     →  FALSE
   *   VECTOR_IS_VALID(NULL)               →  FALSE
   */
  @FunctionTemplate(
      name = "vector_is_valid",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.INTERNAL)
  public static class VectorIsValid implements SimpleFunction {
    @Param  NullableVarCharHolder vec;
    @Output NullableIntHolder     out;   // Dremio maps INT 0/1 to BOOLEAN

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      if (vec.isSet == 0) {
        out.value = 0;
        return;
      }
      byte[] b = new byte[vec.end - vec.start];
      vec.buffer.getBytes(vec.start, b);
      String s = new String(b, java.nio.charset.StandardCharsets.UTF_8);
      out.value = com.dremio.udf.vector.VectorUtils.isValid(s) ? 1 : 0;
    }
  }

  // ── VECTOR_NORMALIZE ──────────────────────────────────────────────────────

  /**
   * Returns a unit-normalized copy of the input vector as a JSON array string.
   * After normalization, DOT_PRODUCT(a, b) == COSINE_SIMILARITY(a, b) and is faster.
   *
   * Example:
   *   VECTOR_NORMALIZE('[3.0, 4.0]')  →  '[0.6,0.8]'
   *   VECTOR_NORM(VECTOR_NORMALIZE(v)) → 1.0  (always)
   */
  @FunctionTemplate(
      name = "vector_normalize",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorNormalize implements SimpleFunction {
    @Param   NullableVarCharHolder vec;
    @Inject  ArrowBuf              buf;
    @Output  NullableVarCharHolder out;

    public void setup() {}

    public void eval() {
      byte[] bIn = new byte[vec.end - vec.start];
      vec.buffer.getBytes(vec.start, bIn);
      String s = new String(bIn, java.nio.charset.StandardCharsets.UTF_8);
      double[] a       = com.dremio.udf.vector.VectorUtils.parseVector(s);
      double[] normed  = com.dremio.udf.vector.VectorUtils.normalize(a);
      String   json    = com.dremio.udf.vector.VectorUtils.toJson(normed);
      byte[]   bOut    = json.getBytes(java.nio.charset.StandardCharsets.UTF_8);
      buf = buf.reallocIfNeeded(bOut.length);
      buf.setBytes(0, bOut);
      out.isSet  = 1;
      out.start  = 0;
      out.end    = bOut.length;
      out.buffer = buf;
    }
  }

  // ── VECTOR_ADD ────────────────────────────────────────────────────────────

  /**
   * Element-wise addition of two vectors. Returns a JSON array string.
   *   VECTOR_ADD('[1.0,2.0,3.0]', '[4.0,5.0,6.0]')  →  '[5.0,7.0,9.0]'
   */
  @FunctionTemplate(
      name = "vector_add",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorAdd implements SimpleFunction {
    @Param   NullableVarCharHolder vec1;
    @Param   NullableVarCharHolder vec2;
    @Inject  ArrowBuf              buf;
    @Output  NullableVarCharHolder out;

    public void setup() {}

    public void eval() {
      byte[] b1 = new byte[vec1.end - vec1.start]; vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start]; vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a  = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      String json = com.dremio.udf.vector.VectorUtils.toJson(
                      com.dremio.udf.vector.VectorUtils.add(a, b));
      byte[] bOut = json.getBytes(java.nio.charset.StandardCharsets.UTF_8);
      buf = buf.reallocIfNeeded(bOut.length);
      buf.setBytes(0, bOut);
      out.isSet = 1; out.start = 0; out.end = bOut.length; out.buffer = buf;
    }
  }

  // ── VECTOR_SUBTRACT ───────────────────────────────────────────────────────

  /**
   * Element-wise subtraction. Returns a JSON array string.
   *   VECTOR_SUBTRACT('[5.0,7.0]', '[1.0,2.0]')  →  '[4.0,5.0]'
   */
  @FunctionTemplate(
      name = "vector_subtract",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorSubtract implements SimpleFunction {
    @Param   NullableVarCharHolder vec1;
    @Param   NullableVarCharHolder vec2;
    @Inject  ArrowBuf              buf;
    @Output  NullableVarCharHolder out;

    public void setup() {}

    public void eval() {
      byte[] b1 = new byte[vec1.end - vec1.start]; vec1.buffer.getBytes(vec1.start, b1);
      byte[] b2 = new byte[vec2.end - vec2.start]; vec2.buffer.getBytes(vec2.start, b2);
      String s1 = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      String s2 = new String(b2, java.nio.charset.StandardCharsets.UTF_8);
      double[] a  = com.dremio.udf.vector.VectorUtils.parseVector(s1);
      double[] b  = com.dremio.udf.vector.VectorUtils.parseVector(s2);
      String json = com.dremio.udf.vector.VectorUtils.toJson(
                      com.dremio.udf.vector.VectorUtils.subtract(a, b));
      byte[] bOut = json.getBytes(java.nio.charset.StandardCharsets.UTF_8);
      buf = buf.reallocIfNeeded(bOut.length);
      buf.setBytes(0, bOut);
      out.isSet = 1; out.start = 0; out.end = bOut.length; out.buffer = buf;
    }
  }

  // ── VECTOR_SCALE ──────────────────────────────────────────────────────────

  /**
   * Multiply every element by a scalar. Returns a JSON array string.
   *   VECTOR_SCALE('[1.0,2.0,3.0]', 2.0)  →  '[2.0,4.0,6.0]'
   *   VECTOR_SCALE('[1.0,2.0,3.0]', 0.5)  →  '[0.5,1.0,1.5]'
   */
  @FunctionTemplate(
      name = "vector_scale",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorScale implements SimpleFunction {
    @Param   NullableVarCharHolder vec;
    @Param   Float8Holder          scalar;
    @Inject  ArrowBuf              buf;
    @Output  NullableVarCharHolder out;

    public void setup() {}

    public void eval() {
      byte[] b1 = new byte[vec.end - vec.start]; vec.buffer.getBytes(vec.start, b1);
      String s   = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s);
      String json = com.dremio.udf.vector.VectorUtils.toJson(
                      com.dremio.udf.vector.VectorUtils.scale(a, scalar.value));
      byte[] bOut = json.getBytes(java.nio.charset.StandardCharsets.UTF_8);
      buf = buf.reallocIfNeeded(bOut.length);
      buf.setBytes(0, bOut);
      out.isSet = 1; out.start = 0; out.end = bOut.length; out.buffer = buf;
    }
  }

  // ── VECTOR_SLICE ──────────────────────────────────────────────────────────

  /**
   * Extract a sub-vector from index start (inclusive) to end (exclusive).
   * Supports Matryoshka embedding truncation.
   *   VECTOR_SLICE('[0.1,0.2,0.3,0.4,0.5]', 1, 4)  →  '[0.2,0.3,0.4]'
   *   VECTOR_SLICE(embedding, 0, 256)  -- first 256 dims of a 1536-dim vector
   */
  @FunctionTemplate(
      name = "vector_slice",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorSlice implements SimpleFunction {
    @Param   NullableVarCharHolder vec;
    @Param   IntHolder             start;
    @Param   IntHolder             end;
    @Inject  ArrowBuf              buf;
    @Output  NullableVarCharHolder out;

    public void setup() {}

    public void eval() {
      byte[] b1 = new byte[vec.end - vec.start]; vec.buffer.getBytes(vec.start, b1);
      String s   = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s);
      String json = com.dremio.udf.vector.VectorUtils.toJson(
                      com.dremio.udf.vector.VectorUtils.slice(a, start.value, end.value));
      byte[] bOut = json.getBytes(java.nio.charset.StandardCharsets.UTF_8);
      buf = buf.reallocIfNeeded(bOut.length);
      buf.setBytes(0, bOut);
      out.isSet = 1; out.start = 0; out.end = bOut.length; out.buffer = buf;
    }
  }

  // ── VECTOR_ELEMENT_AT ─────────────────────────────────────────────────────

  /**
   * Return the element at the given zero-based index. Supports negative indexing.
   *   VECTOR_ELEMENT_AT('[0.1,0.2,0.3]', 0)   →  0.1
   *   VECTOR_ELEMENT_AT('[0.1,0.2,0.3]', -1)  →  0.3  (last element)
   */
  @FunctionTemplate(
      name = "vector_element_at",
      scope = FunctionTemplate.FunctionScope.SIMPLE,
      nulls = FunctionTemplate.NullHandling.NULL_IF_NULL)
  public static class VectorElementAt implements SimpleFunction {
    @Param   NullableVarCharHolder vec;
    @Param   IntHolder             index;
    @Output  NullableFloat8Holder  out;

    public void setup() {}

    public void eval() {
      out.isSet = 1;
      byte[] b1 = new byte[vec.end - vec.start]; vec.buffer.getBytes(vec.start, b1);
      String s   = new String(b1, java.nio.charset.StandardCharsets.UTF_8);
      double[] a = com.dremio.udf.vector.VectorUtils.parseVector(s);
      out.value  = com.dremio.udf.vector.VectorUtils.elementAt(a, index.value);
    }
  }
}
